### PR TITLE
Fix issue where files were downloaded with zero content.

### LINKED ISSUE #2: In some cases, files downloaded but with empty content.
Given the following:

```
./fetch --repo="https://github.com/gruntwork-io/packer-modules" --tag="0.0.1" --github-oauth-token="<igthub-auth-token" /modules/base/ubuntu1604 /tmp/packer-modules/base/ubuntu1604
```

The output is as follows:

```
$ ls -al /tmp/packer-modules/base/ubuntu1604/
total 0
drwxr-xr-x  4 josh  wheel  136 Apr 27 13:49 .
drwxr-xr-x  3 josh  wheel  102 Apr 27 13:49 ..
-rw-r--r--  1 josh  wheel    0 Apr 27 13:49 README.md
-rw-r--r--  1 josh  wheel    0 Apr 27 13:49 ubuntu1604.sh
```

Note that `ubuntu1604.sh` should not have size `0`.

### PR DESCRIPTION
**Pull request by josh-padnick**
- Fixes #2. 
- Added a test to ensure this doesn't break in the future.
- Refined command-line output.

### CODE REVIEW

**Comment by josh-padnick** [comment]
@brikis98 Since you're on vacation right now, I'll auto-merge and cut a new release. Feel free to review when free.

File: file_test.go [hunk 1]
```diff
@@ -118,5 +120,28 @@ func TestExtractFiles(t *testing.T) {
...
+				}
+			}
+			return nil
+		})
+
+	}
+}
+
+// Return ture if the given slice contains the given string
+func stringInSlice(s string, slice []string) bool {
```
Comment (brikis98) [inline file_test.go]: Theorem: every non-trivial Go codebase has at least one copy of this method.

**Comment by brikis98** [comment]
lgtm
