### PR TITLE
Pete/87/broken branch

### LINKED ISSUE #87: fetch no longer works with just --branch
It looks like adding `--ref` in https://github.com/gruntwork-io/fetch/pull/79 may have broken the `--branch` parameter.

With `fetch` version `v0.3.9`:

```
gruntwork-install \
  --module-name "gcp-helpers" \
  --repo "https://github.com/gruntwork-io/terraform-google-ci" \
  --branch "gcp-helpers"
```

Works as follows:

```
2021-02-01 14:10:38 [INFO] [gruntwork-install] Installing from gcp-helpers...
2021-02-01 14:10:38 [INFO] [gruntwork-install] Downloading module gcp-helpers from https://github.com/gruntwork-io/terraform-google-ci
Downloading latest commit from branch "gcp-helpers" of https://github.com/gruntwork-io/terraform-google-ci ...
Extracting files from <repo>/modules/gcp-helpers to /tmp/gruntwork-script-modules/gcp-helpers ...
Download and file extraction complete.
2021-02-01 14:10:39 [INFO] [gruntwork-install] Setting GRUNTWORK_INSTALL_TAG to 
2021-02-01 14:10:39 [INFO] [gruntwork-install] Setting GRUNTWORK_INSTALL_BRANCH to gcp-helpers
2021-02-01 14:10:39 [INFO] [gruntwork-install] Executing /tmp/gruntwork-script-modules/gcp-helpers/install.sh 
```

But with `fetch` version `v0.3.13`:

```
2021-02-01 13:31:02 [INFO] [gruntwork-install] Installing from gcp-helpers...
2021-02-01 13:31:02 [INFO] [gruntwork-install] Downloading module gcp-helpers from https://github.com/gruntwork-io/terraform-google-ci
Downloading git reference "v0.1.0" of https://github.com/gruntwork-io/terraform-google-ci ...
Extracting files from <repo>/modules/gcp-helpers to /tmp/gruntwork-script-modules/gcp-helpers ... 0 files extracted
Download and file extraction complete.
2021-02-01 13:31:02 [ERROR] [gruntwork-install] No files were downloaded. Are you sure "gcp-helpers" is a valid Script Module in https://github.com/gruntwork-io/terraform-google-ci (tag = , branch = gcp-helpers)?
```

I'm guessing [the way `GitRef` is set here to `latestTag`](https://github.com/gruntwork-io/fetch/pull/79/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R285-R295) is causing the code to go down the wrong code path.

### PR DESCRIPTION
**Pull request by pete0emerson**
This closes #87.

This has no additional tests yet.

We don't have specific tests for `MakeGitHubZipFileRequest`, which I modified to put the conditional for GitRef last.

We do test `downloadGithubZipFile` which calls `MakeGitHubZipFileRequest`, and it seems like our test `TestDownloadGitBranchZipFile` would be designed to catch this. Here's the logic that I unwrapped for this particular case:

```
since options.GitRef is not specified
    code detects a tag with a tag constraint

since there is no specific release that matches the version constraint
    latestTag is set to the latest release it can find
    desiredTag is set to latestTag

desiredTag is passed into downloadSourcePaths as latestTag

in func downloadSourcePaths
    GitRef and GitTag are both set to latestTag
    BranchName will exist, as well
    but this is where ordering is important
    GitRef needs to be checked last, otherwise downloading a branch cannot work
```

I'm open to suggestions on improving testing here, it seems like `downloadGithubZipFile` would need to be tested with multiple things set to make sure it does the right action, but I'm not positive.

Here's the evidence of this fixing the problem @brikis98 encountered. I also ran all of the tests, and they're passing.

```
# Test with --branch
 fetch git:(pete/87/broken_branch) $ ./fetch --repo="https://github.com/gruntwork-io/terraform-google-ci" --branch="gcp-helpers" --source-path="/modules/gcp-helpers" "/tmp/download-dir/gcp-helpers"
Downloading latest commit from branch "gcp-helpers" of https://github.com/gruntwork-io/terraform-google-ci ...
Extracting files from <repo>/modules/gcp-helpers to /tmp/download-dir/gcp-helpers ... 3 files extracted
Download and file extraction complete.

# Test with --ref
 fetch git:(pete/87/broken_branch) $ ./fetch --repo="https://github.com/gruntwork-io/terraform-google-ci" --ref="gcp-helpers" --source-path="/modules/gcp-helpers" "/tmp/download-dir/gcp-helpers"
Downloading tag "gcp-helpers" of https://github.com/gruntwork-io/terraform-google-ci ...
Extracting files from <repo>/modules/gcp-helpers to /tmp/download-dir/gcp-helpers ... 3 files extracted
Download and file extraction complete.

# Testing TestDownloadGitBranchZipFile (which wasn't broken before, either)
 fetch git:(pete/87/broken_branch) $ go test -v -run TestDownloadGitBranchZipFile
=== RUN   TestDownloadGitBranchZipFile
=== PAUSE TestDownloadGitBranchZipFile
=== CONT  TestDownloadGitBranchZipFile
--- PASS: TestDownloadGitBranchZipFile (1.37s)
PASS
ok  	github.com/gruntwork-io/fetch	1.529s
```

### CODE REVIEW

**Comment by robmorgan** [comment]
Hey @pete0emerson, 

Thanks for submitting a fix so quickly! I tested your logic locally and I can confirm it works with my use case. In regards to your comments around testing, I think the right way to solve this is with integration tests! That way we can easily assert our intended behavior from a 9000ft view and not in all of these individual functions. I've gone ahead and added one specifically for branches to this PR (more info below), however, since I'm now a contributor to this PR, we'll need to get @brikis98 to review.

#### Integration Tests

Whilst inspired by the [integration tests](https://github.com/gruntwork-io/terragrunt/blob/master/test/integration_test.go) in Terragrunt, this was slightly non-trivial for `fetch` as we write directly to `os.Stdout()` and `os.Stderr()`. Therefore I had to do some voodoo magic in `runFetchCommandWithOutput` to temporarily override these pipes.

Feel free to let me know what you think.

File: file.go [hunk 1]
```diff
@@ -151,14 +151,14 @@ func MakeGitHubZipFileRequest(gitHubCommit GitHubCommit, gitHubToken string, ins
 
 	// This represents either a commit, branch, or git tag
 	var gitRef string
-	if gitHubCommit.GitRef != "" {
-		gitRef = gitHubCommit.GitRef
-	} else if gitHubCommit.CommitSha != "" {
+	if gitHubCommit.CommitSha != "" {
```
Comment (brikis98) [inline file.go:154]: Update the comment above this if-statement to explicitly state that order matters here! You can link to this bug as an example of why.

File: integration_test.go [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+		{"branch option with public repo", "https://github.com/gruntwork-io/fetch-test-public", "sample-branch", "/"},
+
+		// Private repo equivalent
+		{"branch option with private repo", "https://github.com/gruntwork-io/fetch-test-private", "sample-branch", "/"},
+	}
+
+	for _, tc := range cases {
+		tc := tc
+
+		t.Run(tc.name, func(t *testing.T) {
```
Comment (brikis98) [inline integration_test.go:38]: Add `t.Parallel()`?

File: integration_test.go [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+	}{
+		// Test on a public repo whose sole purpose is to be a test fixture for this tool
+		{"branch option with public repo", "https://github.com/gruntwork-io/fetch-test-public", "sample-branch", "/"},
+
+		// Private repo equivalent
+		{"branch option with private repo", "https://github.com/gruntwork-io/fetch-test-private", "sample-branch", "/"},
+	}
+
+	for _, tc := range cases {
+		tc := tc
```
Comment (brikis98) [inline integration_test.go:36]: NIT: add our usual comment block.

```go
    // The following is necessary to make sure tc's values don't
    // get updated due to concurrency within the scope of t.Run(..) below
```

File: integration_test.go [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+
+		t.Run(tc.name, func(t *testing.T) {
+			cmd := fmt.Sprintf("fetch --repo %s --branch %s --source-path %s %s", tc.repoUrl, tc.branchName, tc.sourcePath, tmpDownloadPath)
+			//t.Fatal(cmd)
```
Comment (brikis98) [inline integration_test.go:40]: NIT: Remove?

File: integration_test.go [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+			output, _, err := runFetchCommandWithOutput(t, cmd)
+			require.NoError(t, err)
+
+			// When --branch is specified, ensure the latest commit is fetched
+			assert.Contains(t, output, "Downloading latest commit from branch")
```
Comment (brikis98) [inline integration_test.go:45]: Is there some file in that branch we could check instead of `stdout`? Might simplify the test and make it more robust against minor logging changes.

File: main.go [hunk 6]
```diff
@@ -290,14 +302,14 @@ func downloadSourcePaths(sourcePaths []string, destPath string, githubRepo GitHu
 
 	// Download that release as a .zip file
 
-	if gitHubCommit.GitRef != "" {
-		fmt.Printf("Downloading git reference \"%s\" of %s ...\n", gitHubCommit.GitRef, githubRepo.Url)
-	} else if gitHubCommit.CommitSha != "" {
+	if gitHubCommit.CommitSha != "" {
```
Comment (brikis98) [inline main.go:305]: Add the same comment here too

**Review by brikis98 — COMMENTED** [review]
Thanks Pete and Rob!

File: integration_test.go (hunk 2 above)
Comment (robmorgan) [reply integration_test.go:38]: @brikis98 hmmm I'm a bit skeptical of a `t.Parallel()` because I'm doing a dodgy hack to override `os.Stdout` and `os.Stderr`. Should I simply comment I'm deliberately not doing that instead?

File: integration_test.go (hunk 3 above)
Comment (robmorgan) [reply integration_test.go:36]: @brikis98 see my comment above. Should I skip this comment as I don't think they'll run in parallel?

File: integration_test.go (hunk 4 above)
Comment (robmorgan) [reply integration_test.go:40]: Yep, thx!

File: integration_test.go (hunk 5 above)
Comment (robmorgan) [reply integration_test.go:45]: @brikis98 Yeah, there are two files specifically added in that branch in both repos, BUT if that branch exists with a particular Git tag, then this test might pass with an older version of the said branch. We don't want to allow that behavior as we want the latest commit. I tried to only assert for a subset of the output to future-proof it. Maybe I could look up the latest commit manually or hard-code it as the branches haven't changed in 5 years?

File: integration_test.go (hunk 2 above)
Comment (brikis98) [reply integration_test.go:38]: Let's resolve how the test will work below. If we stick with weird `stdout` stuff, then yea, commenting it out explicitly and explaining why is  good idea.

File: integration_test.go (hunk 5 above)
Comment (brikis98) [reply integration_test.go:45]: Perhaps create a totally new branch, specifically for testing? Call it something like `branch-for-testing`. There should be no tag of that name or any other conflict to worry about.

Comment (brikis98) [reply integration_test.go:45]: (Create a totally new branch and totally new file in that branch, that is)

Comment (robmorgan) [reply integration_test.go:45]: @brikis98 we'll we kind of already have that, see: https://github.com/gruntwork-io/fetch-test-public/tree/sample-branch. Two [files get added](https://github.com/gruntwork-io/fetch-test-public/compare/sample-branch). I'm of the opinion we should actually assert for both the text as I've done and whether or not the file exists.

Because we can continue to use the new integration helper methods like `runFetchCommandWithOutput` until we eventually move our `fetch` code over to use an inbuilt logger.

Comment (robmorgan) [reply integration_test.go:45]: Eventually, we can add more integration tests for other use cases.

Comment (brikis98) [reply integration_test.go:45]: Ah, if we already have those files in such a branch, then I think checking for those files is enough... We don't need the fancy `stdout` check. We could even run the code explicitly against `master` branch and than this `sample-branch` and ensure the files you see are different!

Comment (robmorgan) [reply integration_test.go:45]: @brikis98 yeah, I previously ran it against `master` as it will always exist but I noticed Josh created these branches that look like they are exclusively used for testing. The only problem I have with removing the `stdout` check is whilst it's not ideal, we miss the opportunity to write further integration tests in the future. I'm of the opinion it would be better to leave functions like `runFetchCommand` and `runFetchCommandWithOutput` in, to properly test command output. In the long run, I think the right solution is to refactor the code to avoid writing directly to those streams and then removing the hacks in the test suite.

Comment (robmorgan) [reply integration_test.go:45]: For instance, you can see how we do this properly in Terragrunt: https://github.com/gruntwork-io/terragrunt/blob/master/test/integration_test.go

Comment (brikis98) [reply integration_test.go:45]: I think the real solution is to switch `fetch` to use a proper logger. That way, we'd have log levels, logs would go to `stderr`, we could swap in a logger more easily that captures the output in tests, and so on. But that's a fair bit of work.

Your call on whether to leave the `stdout` check that's there now or not! I don't feel strongly either way.

Comment (robmorgan) [reply integration_test.go:45]: Yes, I think we're in alignment now. I'm not sure if you missed the fact I mentioned a logger above:

> Because we can continue to use the new integration helper methods like runFetchCommandWithOutput until we eventually move our fetch code over to use an inbuilt logger.

I'm under the opinion that this is non-ideal, but moving in the right direction, so I'm going to leave it as is, but improve the test cases and mention why I'm not running the tests in parallel. Eventually, we can introduce a logger.

**Comment by brikis98** [comment]
Roger!

File: integration_test.go (hunk 3 above)
Comment (robmorgan) [reply integration_test.go:36]: done.

File: integration_test.go (hunk 4 above)
Comment (robmorgan) [reply integration_test.go:40]: done.

File: file.go (hunk 1 above)
Comment (robmorgan) [reply file.go:154]: @pete0emerson leaving this one for you

File: integration_test.go (hunk 5 above)
Comment (robmorgan) [reply integration_test.go:45]: Resolving this one, but opened a separate ticket to track the issue: https://github.com/gruntwork-io/fetch/issues/89

Comment (robmorgan) [reply integration_test.go:45]: fixed in latest commit.

File: integration_test.go (hunk 2 above)
Comment (robmorgan) [reply integration_test.go:38]: added a comment on why I'm not using parallelism.

File: file.go (hunk 1 above)
Comment (brikis98) [reply file.go:154]: @pete0emerson Do you want to make this change so we can wrap this PR up?

Comment (pete0emerson) [reply file.go:157]: Addressed in e088d3b

File: main.go (hunk 6 above)
Comment (pete0emerson) [reply main.go:308]: Addressed in e088d3b

**Review by brikis98 — APPROVED** [review]
LGTM, thx Pete and Rob!

Pete, could you release a new version?

**Comment by robmorgan** [comment]
New version released in https://github.com/gruntwork-io/fetch/releases/tag/v0.3.14
